ALTER TABLE "account_groups" ADD CONSTRAINT "account_groups_organization_id_unique" UNIQUE("organization_id","id");--> statement-breakpoint
ALTER TABLE "campaigns" ADD CONSTRAINT "campaigns_organization_id_unique" UNIQUE("organization_id","id");--> statement-breakpoint
ALTER TABLE "instagram_accounts" ADD CONSTRAINT "instagram_accounts_organization_id_unique" UNIQUE("organization_id","id");--> statement-breakpoint
ALTER TABLE "media_assets" ADD CONSTRAINT "media_assets_organization_id_unique" UNIQUE("organization_id","id");--> statement-breakpoint
ALTER TABLE "media_folders" ADD CONSTRAINT "media_folders_organization_id_unique" UNIQUE("organization_id","id");--> statement-breakpoint
ALTER TABLE "publication_jobs" ADD CONSTRAINT "publication_jobs_organization_id_unique" UNIQUE("organization_id","id");--> statement-breakpoint
ALTER TABLE "account_daily_metrics" ADD CONSTRAINT "account_daily_metrics_organization_account_fk" FOREIGN KEY ("organization_id","instagram_account_id") REFERENCES "public"."instagram_accounts"("organization_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account_group_members" ADD CONSTRAINT "account_group_members_organization_group_fk" FOREIGN KEY ("organization_id","group_id") REFERENCES "public"."account_groups"("organization_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account_group_members" ADD CONSTRAINT "account_group_members_organization_account_fk" FOREIGN KEY ("organization_id","instagram_account_id") REFERENCES "public"."instagram_accounts"("organization_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account_media" ADD CONSTRAINT "account_media_organization_account_fk" FOREIGN KEY ("organization_id","instagram_account_id") REFERENCES "public"."instagram_accounts"("organization_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_media" ADD CONSTRAINT "campaign_media_organization_campaign_fk" FOREIGN KEY ("organization_id","campaign_id") REFERENCES "public"."campaigns"("organization_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_media" ADD CONSTRAINT "campaign_media_organization_asset_fk" FOREIGN KEY ("organization_id","media_asset_id") REFERENCES "public"."media_assets"("organization_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_targets" ADD CONSTRAINT "campaign_targets_organization_campaign_fk" FOREIGN KEY ("organization_id","campaign_id") REFERENCES "public"."campaigns"("organization_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_targets" ADD CONSTRAINT "campaign_targets_organization_account_fk" FOREIGN KEY ("organization_id","instagram_account_id") REFERENCES "public"."instagram_accounts"("organization_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth_states" ADD CONSTRAINT "oauth_states_organization_member_fk" FOREIGN KEY ("organization_id","initiated_by") REFERENCES "public"."organization_members"("organization_id","user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "publication_jobs" ADD CONSTRAINT "publication_jobs_organization_campaign_fk" FOREIGN KEY ("organization_id","campaign_id") REFERENCES "public"."campaigns"("organization_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "publication_jobs" ADD CONSTRAINT "publication_jobs_organization_account_fk" FOREIGN KEY ("organization_id","instagram_account_id") REFERENCES "public"."instagram_accounts"("organization_id","id") ON DELETE restrict ON UPDATE no action;
